version: "3"

services:
  db:
    image: postgres:14
    env_file:
      - ./app/.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata

  notebooks:
    image: tfa-notebooks
    depends_on:
      - db
    build:
      context: notebooks
      dockerfile: Dockerfile
    env_file:
      - ./app/.env
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/tfa/notebooks

  app:
    image: tfa-app
    depends_on:
      - db
    build:
      context: app
      dockerfile: Dockerfile
    env_file:
      - ./app/.env
    ports:
      - 8000:8000
    volumes:
      - ./app:/tfa/app/

  web:
    image: tfa-web
    depends_on:
      - app
    build:
      context: web
      dockerfile: Dockerfile
    env_file:
      - ./web/.env
    ports:
      - 8080:8080
    volumes:
      - ./web:/tfa/web/

volumes:
  app-db-data:
