"""empty message

Revision ID: 22ea6fa4ec33
Revises: 7da7fa8f4d36
Create Date: 2023-08-27 09:09:46.661619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22ea6fa4ec33'
down_revision = '7da7fa8f4d36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topups',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('topup_date', sa.DateTime(), nullable=False),
    sa.Column('balance_id', sa.BigInteger(), nullable=False),
    sa.Column('topup_amount', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topup_date', 'balance_id', name='unique_topup')
    )
    op.create_index(op.f('ix_topups_balance_id'), 'topups', ['balance_id'], unique=False)
    op.create_index(op.f('ix_topups_topup_date'), 'topups', ['topup_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topups_topup_date'), table_name='topups')
    op.drop_index(op.f('ix_topups_balance_id'), table_name='topups')
    op.drop_table('topups')
    # ### end Alembic commands ###
