"""empty message

Revision ID: 7da7fa8f4d36
Revises: c9f71666811c
Create Date: 2023-08-27 08:32:10.077557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7da7fa8f4d36'
down_revision = 'c9f71666811c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecasts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('forecast_date', sa.DateTime(), nullable=False),
    sa.Column('balance_id', sa.BigInteger(), nullable=False),
    sa.Column('forecast_amount', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('forecast_date', 'balance_id', name='unique_forecast')
    )
    op.create_index(op.f('ix_forecasts_balance_id'), 'forecasts', ['balance_id'], unique=False)
    op.create_index(op.f('ix_forecasts_forecast_date'), 'forecasts', ['forecast_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forecasts_forecast_date'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_balance_id'), table_name='forecasts')
    op.drop_table('forecasts')
    # ### end Alembic commands ###
