"""empty message

Revision ID: fdd6cf7610c2
Revises: 
Create Date: 2023-07-19 18:35:04.909733

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fdd6cf7610c2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "balance_movements",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("sending_partner_id", sa.BigInteger(), nullable=False),
        sa.Column("receiving_partner_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "balance_movement_amount", sa.Numeric(precision=24, scale=8), nullable=False
        ),
        sa.Column("balance_movement_date", sa.DateTime(), nullable=False),
        sa.Column("balance_id", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "sending_partner_id",
            "receiving_partner_id",
            "balance_movement_date",
            "balance_id",
            name="unique_balance_movement",
        ),
    )
    op.create_index(
        op.f("ix_balance_movements_balance_id"),
        "balance_movements",
        ["balance_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_balance_movements_receiving_partner_id"),
        "balance_movements",
        ["receiving_partner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_balance_movements_sending_partner_id"),
        "balance_movements",
        ["sending_partner_id"],
        unique=False,
    )

    op.create_table(
        "receiving_partner_balances",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("balance_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "available_balance", sa.Numeric(precision=24, scale=8), nullable=False
        ),
        sa.Column("balance_snapshot_date", sa.DateTime(), nullable=False),
        sa.Column(
            "creation_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "balance_id",
            "balance_snapshot_date",
            name="unique_receiving_partner_balance",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("receiving_partner_balances")
    op.drop_index(
        op.f("ix_balance_movements_sending_partner_id"), table_name="balance_movements"
    )
    op.drop_index(
        op.f("ix_balance_movements_receiving_partner_id"),
        table_name="balance_movements",
    )
    op.drop_index(
        op.f("ix_balance_movements_balance_id"), table_name="balance_movements"
    )
    op.drop_table("balance_movements")
    # ### end Alembic commands ###
